export enum JournalEntryType {
  AIPrompt = "ai",
  Blank = "blank",
  Morning = "morning",
  Night = "night",
  Todo = "todo",
  Voice = "voice",
  Camera = "camera",
  Gratitude = "gratitude",
  MentalHealth = "mental-health",
  Organization = "organization",
  Creative = "creative",
  Relationships = "relationships",
  PersonalGrowth = "personal-growth",
}
export enum JournalTemplate {
  AIPrompt = "AI Guided Journal",
  Blank = "Free Writing",
  Morning = "Morning Intentions",
  Night = "Night Reflections",
  Todo = "Todo Journal",
  Voice = "Voice Journal",
  Camera = "Written Journal",
  Gratitude = "Gratitude Journal",
  // New templates
  HighLow = "High/Low of the Day",
  AnxietyCheckin = "Anxiety Check-in",
  MoodTracker = "Mood Tracker",
  ThoughtChallenge = "Thought Challenge",
  SelfCompassion = "Self-Compassion Exercise",
  EmotionalInventory = "Emotional Inventory",
  CopingStrategies = "Coping Strategies",
  PriorityTasks = "Priority Tasks",
  WeeklyGoals = "Weekly Goals",
  BrainDump = "Brain Dump",
  MeetingNotes = "Meeting Notes",
  ProjectPlanning = "Project Planning",
  HabitTracker = "Habit Tracker",
  FreeWriting = "Free Writing",
  PoetryStarter = "Poetry Starter",
  CharacterSketch = "Character Sketch",
  DialoguePrompt = "Dialogue Prompt",
  StoryIdeas = "Story Ideas",
  ArtistDate = "Artist Date Reflection",
  RelationshipAppreciation = "Relationship Appreciation",
  CommunicationReflection = "Communication Reflection",
  SocialEnergy = "Social Energy Check-in",
  BoundarySetting = "Boundary Setting",
  ConflictResolution = "Conflict Resolution",
  GratitudeForOthers = "Gratitude for Others",
  ValuesAlignment = "Values Alignment",
  LifeVision = "Life Vision",
  SkillDevelopment = "Skill Development",
  ObstacleAnalysis = "Obstacle Analysis",
  SuccessCelebration = "Success Celebration",
  LessonLearning = "Lesson Learning",
  WeeklyReview = "Weekly Review",
  MindfulMoment = "Mindful Moment",
}
export enum JournalTemplateID {
  AIPrompt = 0,
  Blank = 1,
  Morning1 = 2,
  Night1 = 3,
  Todo = 4,
  Voice = 5,
  Camera = 6,
  Gratitude = 7,
  Goals = 8,
  // New template IDs
  HighLow = 9,
  AnxietyCheckin = 10,
  MoodTracker = 11,
  ThoughtChallenge = 12,
  SelfCompassion = 13,
  EmotionalInventory = 14,
  CopingStrategies = 15,
  PriorityTasks = 16,
  WeeklyGoals = 17,
  BrainDump = 18,
  MeetingNotes = 19,
  ProjectPlanning = 20,
  HabitTracker = 21,
  FreeWriting = 22,
  PoetryStarter = 23,
  CharacterSketch = 24,
  DialoguePrompt = 25,
  StoryIdeas = 26,
  ArtistDate = 27,
  RelationshipAppreciation = 28,
  CommunicationReflection = 29,
  SocialEnergy = 30,
  BoundarySetting = 31,
  ConflictResolution = 32,
  GratitudeForOthers = 33,
  ValuesAlignment = 34,
  LifeVision = 35,
  SkillDevelopment = 36,
  ObstacleAnalysis = 37,
  SuccessCelebration = 38,
  LessonLearning = 39,
  WeeklyReview = 40,
  MindfulMoment = 41,
}

export enum Entries {
  Journal = "journal",
  CheatSheet = "cheatSheet",
  Goals = "goals",
  Users = "users",
}
